---
title: "Iris_Q1: Looking at Sepal Length"
author: "Sarah Gartenmann"
date: "5 May 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting Ready

Loading the packages
Importing the csv file with the data

...

```{r getting ready}

#loading packages
library(tidyverse)
library(dplyr)
library(ggplot2)

#importing data
getwd()
iris <- read_csv('iris.csv')

#taking a look
summary(iris)
head(iris)

```

## Looking at Sepal Length

```{r data exploration}

plot_SepalLength <- ggplot(iris, aes(x = iris$Sepal.Length, y = ..count.., col = Species, fill = Species)) +
  geom_bar(show.legend = FALSE) +
  scale_x_continuous(limit = c(4,8), breaks = seq(4,8, by = 1)) +
  scale_y_continuous(limit = c(0, 8), breaks = seq(0, 8, by = 1)) +
  labs(title = "Differences in Iris Sepal Length",
      subtitle = "Visualising the Distribution of Sepal Length as a Function of Species") +
  xlab("Iris Sepal Length") +
  ylab("Number of Iris") +
  facet_wrap(~Species)

plot_SepalLength


```